long_uptime = true
physical_cores = true

show = [
  "Host",
  "Machine",
  "Kernel",
  "Distribution",
  "OperatingSystem",
  "Packages",
  "Shell",
  "Terminal",
  "Uptime",
  "Memory",
  "GPU",
  "Processor",
  "ProcessorLoad",
  "DiskSpace"
]

disks = ["/home/"]

theme = "monkey"
