padding = 0
spacing = 2
separator = ""
hide_ascii = false

[bar]
glyph = "o"
hide_delimiters = true
visible = false

[box]
visible=false

[custom_ascii]
color = "red"
path = "~/.config/macchina/themes/monkey.txt"
